// Centralized theme definitions — single source of truth for both preview and PDF export
export const THEMES = {
  'classic-fiction': {
    id: 'classic-fiction',
    name: 'Novela Clásica',
    description: 'Garamond con sangría. Capítulos a 1/3 de página. El estándar de la gran literatura.',
    fonts: 'Times / Serif elegante',
    genre: 'Ficción',
    accent: '#2C1810',
    bg: '#FFFDF8',
    // PDF
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 12,
    titleSize: 22,
    lineSpacing: 0.215,
    paragraphSpacing: 0.06,
    chapterStartRatio: 0.32,
    indent: 0.28,
    titleUpperCase: false,
    titleItalic: false,
    titleBold: false,
    decorator: '— ❧ —',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.75,
    bottomMargin: 0.75,
  },
  'non-fiction': {
    id: 'non-fiction',
    name: 'No Ficción / Ensayo',
    description: 'Encabezados jerárquicos. Párrafos sin sangría. Alta legibilidad para lectura de referencia.',
    fonts: 'Helvetica / Sans moderna',
    genre: 'No Ficción',
    accent: '#1A3A5C',
    bg: '#FAFAFA',
    bodyFont: 'helvetica' as const,
    titleFont: 'helvetica' as const,
    fontSize: 11,
    titleSize: 20,
    lineSpacing: 0.195,
    paragraphSpacing: 0.18,
    chapterStartRatio: 0.22,
    indent: 0,
    titleUpperCase: true,
    titleItalic: false,
    titleBold: true,
    decorator: '───',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 1.0,
    outerMargin: 0.75,
    topMargin: 1.0,
    bottomMargin: 0.875,
  },
  'workbook': {
    id: 'workbook',
    name: 'Libro de Trabajo',
    description: 'Márgenes amplios para notas. Espaciado generoso. Tipografía de máxima claridad.',
    fonts: 'Helvetica / Estructural',
    genre: 'Educativo',
    accent: '#1E4D2B',
    bg: '#F8FAF8',
    bodyFont: 'helvetica' as const,
    titleFont: 'helvetica' as const,
    fontSize: 11,
    titleSize: 18,
    lineSpacing: 0.23,
    paragraphSpacing: 0.22,
    chapterStartRatio: 0.18,
    indent: 0,
    titleUpperCase: false,
    titleItalic: false,
    titleBold: true,
    decorator: '▪',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 1.125,
    outerMargin: 0.875,
    topMargin: 1.0,
    bottomMargin: 0.875,
  },
  'sci-fi': {
    id: 'sci-fi',
    name: 'Ciencia Ficción',
    description: 'Courier para inmersión técnica. Capítulos abruptos sin ornamentos. Tensión visual.',
    fonts: 'Courier / Monoespaciada',
    genre: 'Ciencia Ficción',
    accent: '#0D1F2D',
    bg: '#F6F8FA',
    bodyFont: 'courier' as const,
    titleFont: 'courier' as const,
    fontSize: 10.5,
    titleSize: 18,
    lineSpacing: 0.205,
    paragraphSpacing: 0.12,
    chapterStartRatio: 0.25,
    indent: 0,
    titleUpperCase: true,
    titleItalic: false,
    titleBold: true,
    decorator: '///',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.875,
    bottomMargin: 0.75,
  },
  'romance': {
    id: 'romance',
    name: 'Romance y Poesía',
    description: 'Times cursiva para títulos. Sangría fluida. Alta calidez tipográfica.',
    fonts: 'Times / Serif romántica',
    genre: 'Romance',
    accent: '#6B2D42',
    bg: '#FFFBFC',
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 12,
    titleSize: 20,
    lineSpacing: 0.22,
    paragraphSpacing: 0.08,
    chapterStartRatio: 0.35,
    indent: 0.3,
    titleUpperCase: false,
    titleItalic: true,
    titleBold: false,
    decorator: '~ ✦ ~',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.75,
    bottomMargin: 0.75,
  },
  'fantasy': {
    id: 'fantasy',
    name: 'Fantasía Épica',
    description: 'Títulos mayúsculas ornamentales. Sangría clásica. Inmersión total en el mundo.',
    fonts: 'Times / Serif épica',
    genre: 'Fantasía',
    accent: '#2D1B4E',
    bg: '#FDFBF6',
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 11.5,
    titleSize: 22,
    lineSpacing: 0.215,
    paragraphSpacing: 0.07,
    chapterStartRatio: 0.30,
    indent: 0.28,
    titleUpperCase: true,
    titleItalic: false,
    titleBold: false,
    decorator: '⸻ ✦ ⸻',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.875,
    bottomMargin: 0.75,
  },
  'thriller': {
    id: 'thriller',
    name: 'Thriller / Suspenso',
    description: 'Texto compacto. Sin sangría. Alta tensión en el ritmo visual. Capítulos cortos e impactantes.',
    fonts: 'Helvetica / Tensa',
    genre: 'Thriller',
    accent: '#1A1A1A',
    bg: '#F8F8F8',
    bodyFont: 'helvetica' as const,
    titleFont: 'helvetica' as const,
    fontSize: 11,
    titleSize: 19,
    lineSpacing: 0.19,
    paragraphSpacing: 0.14,
    chapterStartRatio: 0.20,
    indent: 0,
    titleUpperCase: true,
    titleItalic: false,
    titleBold: true,
    decorator: '■',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.875,
    bottomMargin: 0.75,
  },
  'academic': {
    id: 'academic',
    name: 'Académico / Técnico',
    description: 'Numeración de capítulos visible. Márgenes amplios para citaciones. Formato APA-friendly.',
    fonts: 'Times / Académica',
    genre: 'Académico',
    accent: '#1A2744',
    bg: '#FAFAFA',
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 12,
    titleSize: 18,
    lineSpacing: 0.225,
    paragraphSpacing: 0.2,
    chapterStartRatio: 0.20,
    indent: 0,
    titleUpperCase: false,
    titleItalic: false,
    titleBold: true,
    decorator: '',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 1.125,
    outerMargin: 1.0,
    topMargin: 1.0,
    bottomMargin: 1.0,
  },
  'poetry': {
    id: 'poetry',
    name: 'Poemario / Lírica',
    description: 'Centrado en la página. Tipografía serif delicada. Cada poema respira en su propio espacio.',
    fonts: 'Times / Lírica',
    genre: 'Poesía',
    accent: '#3D2B1F',
    bg: '#FFFEF8',
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 12,
    titleSize: 16,
    lineSpacing: 0.26,
    paragraphSpacing: 0.35,
    chapterStartRatio: 0.38,
    indent: 0,
    titleUpperCase: false,
    titleItalic: true,
    titleBold: false,
    decorator: '·',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 1.25,
    outerMargin: 1.0,
    topMargin: 1.0,
    bottomMargin: 1.0,
  },
  'memoir': {
    id: 'memoir',
    name: 'Memorias / Autobiografía',
    description: 'Calidez personal. Sangría moderada. Serif legible. Diseño que evoca recuerdos.',
    fonts: 'Times / Personal',
    genre: 'Memorias',
    accent: '#4A3728',
    bg: '#FFFCF7',
    bodyFont: 'times' as const,
    titleFont: 'times' as const,
    fontSize: 12,
    titleSize: 20,
    lineSpacing: 0.22,
    paragraphSpacing: 0.10,
    chapterStartRatio: 0.28,
    indent: 0.25,
    titleUpperCase: false,
    titleItalic: true,
    titleBold: false,
    decorator: '— ◆ —',
    pageNumberStyle: 'bottom-center' as const,
    innerMargin: 0.875,
    outerMargin: 0.625,
    topMargin: 0.75,
    bottomMargin: 0.75,
  },
} as const;

export type ThemeKey = keyof typeof THEMES;
export type ThemeConfig = typeof THEMES[ThemeKey];

export function getTheme(id: string): ThemeConfig {
  return THEMES[id as ThemeKey] ?? THEMES['classic-fiction'];
}
